spring:
  application:
    name: Club-Master
  config:
    import: optional:secrets.properties
  datasource:
    url: jdbc:postgresql://dpg-ctg1qnhopnds73b16rt0-a.frankfurt-postgres.render.com/${db.schema}
    username: ${db.username}
    password: ${db.password}
  flyway:
    enabled: true
#    user: ${db.username}
#    password: ${db.password}
#    schemas: ${db.schema}
    locations: filesystem:db/migration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false

server:
  port: 7443